---
language: bash

install:
  - rvm use 2.2.2 --install --binary --fuzzy
  - git clone https://github.com/sstephenson/bats
  - git clone https://github.com/vinsonchuong/bash-common-parse-options
  - export PATH=$PWD/bin:$PWD/bats/bin:$PWD/bash-common-parse-options/bin:$PATH
script:
  - bats spec
