#!/usr/bin/env bash
set -o errexit
set -o nounset
# set -o xtrace
set -o pipefail

path=$1
source "$(dirname "$0")/../versions"

mkdir -p "$path"
cd "$path"

gem install bundler
cat <<-RUBY > 'Gemfile'
	source 'https://rubygems.org'
	ruby '${RUBY_VERSION}'
	gem 'rails', '~> ${RAILS_VERSION}'
	RUBY
bundle install
bundle exec rails new . \
	--skip-gemfile \
	--skip-bundle
