#!/usr/bin/env bash
set -o errexit
set -o nounset
# set -o xtrace
set -o pipefail

path=$1
lib=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
source "${lib}/../versions"

mkdir -p "$path"
cd "$path"

gem install bundler
cat <<-RUBY > 'Gemfile'
	source 'https://rubygems.org'
	ruby '${RUBY_VERSION}'
	gem 'rails', '~> ${RAILS_VERSION}'
	RUBY
bundle install --jobs 20 --retry 5
bundle exec rails new . \
	--template="${lib}/template.rb" \
	--skip-bundle \
	--database='postgresql' \
	--skip-turbolinks \
	--skip-test-unit \
	--force
