#!/usr/bin/env bash
set -o errexit
set -o nounset
# set -o xtrace
set -o pipefail

path=$1
lib=$(dirname "$(readlink -f "$0")")
source "${lib}/../versions"

prototypical base "$path"
cd "$path"

gem install bundler
cat <<-RUBY > 'Gemfile'
	source 'https://rubygems.org'
	ruby '${RUBY_VERSION}'
	gem 'rails', '~> ${RAILS_VERSION}'
	RUBY
bundle install --jobs 4 --retry 3
bundle exec rails new . \
	--template="${lib}/template.rb" \
	--skip-bundle \
	--database='postgresql' \
	--skip-turbolinks \
	--skip-test-unit \
	--force
