#!/usr/bin/env bash
set -o errexit
set -o nounset
# set -o xtrace
set -o pipefail

lib=$(dirname "$(dirname "$(readlink -f "$0")")")
path=$1
source "${lib}/versions"

project_dir=$(basename "$path")
project_snake=$(echo "$project_dir" | perl -ne 'print join _, split /\W+/')
project_title=$(echo "$project_snake" | perl -ne 'print join " ", map {ucfirst} split _')
project_class=$(echo "$project_title" | perl -ne 'print join "", split " "')
project_camel=$(echo "$project_class" | perl -ne 'print lcfirst')

hub_config="$HOME/.config/hub"
if [[ -f $hub_config || -h $hub_config ]]
then
	github_username=$(ruby -r yaml -e 'puts YAML.load(STDIN.read)["github.com"].first["user"]' < "$hub_config" || echo 'GITHUB_USERNAME')
else
	github_username='GITHUB_USERNAME'
fi

echo "Creating prototypical project at ${path}" >&2
mkdir -p "$path"
cd "$path"

git init 1>&2

echo 'Adding MIT License' >&2
cat <<TEXT > LICENSE
The MIT License (MIT)

Copyright (c) $(date '+%Y') $(git config --get user.name)

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
TEXT

echo 'Adding README.md' >&2
cat <<MARKDOWN > README.md
# ${project_title}
[![Build Status](https://travis-ci.org/${github_username}/${project_dir}.svg?branch=master)](https://travis-ci.org/${github_username}/${project_dir})
MARKDOWN

echo 'Adding generic .travis.yml' >&2
ruby -r 'yaml' <<RUBY > '.travis.yml'
puts YAML.dump(
  'sudo' => 'required',
  'dist' => 'trusty',
  'services' => %w[postgresql],
  'language' => 'generic',
  'before_install' => [
    'export DISPLAY=:99.0',
    'Xvfb :99 -ac -screen 0 1024x768x8 &>/dev/null &',

    'mkdir phantomjs',
    'curl -O https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-14.04.tar.bz2',
    'tar -xf phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C phantomjs',
    'export PATH=$PWD/phantomjs:$PATH'
  ]
)
RUBY

cat <<BASH
$(cat "${lib}/versions")
export path=$(printf '%q' "$path")
export lib=$(printf '%q' "$lib")

export project_dir=$(printf '%q' "$project_dir")
export project_snake=$(printf '%q' "$project_snake")
export project_title=$(printf '%q' "$project_title")
export project_class=$(printf '%q' "$project_class")
export project_camel=$(printf '%q' "$project_camel")

export github_username=$(printf '%q' "$github_username")

cd $(printf '%q' "$path")
BASH
